version: '2'
services:

    nginx:
        build: docker/nginx
        volumes_from:
            - fpm
        restart: always
        tty: true
        stdin_open: true
        working_dir: /
        ports:
            - "8080:2525"
        environment:
            TZ: America/New_York

    fpm:
        build: docker/fpmphp
        volumes:
            - .:/application
        working_dir: /application
        restart: always
        tty: true
        stdin_open: true
        expose:
            - 9000
        env_file:
            - .env.loc
            - .mysql.env.loc

    database:
        build: docker/mysql
        restart: always
        tty: true
        stdin_open: true
        volumes:
            - ./mysqldb:/var/lib/mysql
        expose:
            - 3306
        env_file:
            - .env.loc
            - .mysql.env.loc
